---
title: "P8130_final_project"
author: "Yifei Yu"
date: "2024-12-03"
output:pdf_document
editor_options: 
  chunk_output_type: console
  fontsize: 12pt
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(car)
library(leaps)
library(lmtest)
library(regressinator)
library(broom)
library(modelr)
library(pROC)
library(rsample)
library(survival)
library(dplyr)
library(tidyr)
library(ggsurvfit)
library(survminer)
library(bookdown)
set.seed(11)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

survival_df = read_csv("data/Project_2_data.csv") |>
  janitor::clean_names() |>
  mutate(
    race = factor(race),
    marital_status = factor(marital_status),
    t_stage = factor(t_stage),
    n_stage = factor(n_stage),
    x6th_stage = factor(x6th_stage),
    differentiate = factor(differentiate),
    grade = factor(grade),
    a_stage = factor(a_stage),
    estrogen_status = factor(estrogen_status),
    progesterone_status = factor(progesterone_status),
    status = factor(status)
  ) |>
  mutate(
    differentiate = factor(differentiate, levels = c("Well differentiated", 
                                                     "Moderately differentiated",
                                                     "Poorly differentiated",
                                                     "Undifferentiated")),
    differentiate = relevel(differentiate, ref = "Well differentiated")
  )
```

## Abstract


## Introduction

The data we used for this analysis originates from a breast cancer survival dataset collected from a prospective study. The dataset contains 14 important variables, including patients’ age, race, marital status, tumor size, cancer stages (T Stage, N Stage, and 6th Stage), estrogen and progesterone status, and regional node involvement. The dataset also records patients’ survival times in months and their final survival status (dead or alive). Our objective is to develop models that predict the risk of death among breast cancer patients using these features. Specifically, we aim to identify which variables significantly impact patients’ survival outcomes, determine (potential interactions among the variables, and assess the performance of the models across racial groups). Additionally, we will investigate fairness in the model predictions to ensure equitable accuracy between the majority race group “White” and the minority “Black”.

## Methods


This report was conducted using `survival_data`, which contains information about breast cancer patients from a prospective study. The dimension of this dataset is \texttt{`r nrow(survival_df)` rows and `r ncol(survival_df)` columns}. It contains five numeric variables, which are `age`, `tumor_size`, `regional_node_examined`, `reginol_node_positive`, and `survival_months`, and eleven categorical variables, which are `race`, `marital_status`, `t_stage`, `n_stage`, `x6th_stage`, `differentiate`, `grade`, `a_stage`, `estrogen_status`, `progesterone_status`, and `status`. Key variables in the dataset include:

**age**: The age of the patient (in years).

**differentiate**: Tumor differentiation grade, categorized as "Well differentiated", "Moderately differentiated", "Poorly differentiated", or "Undifferentiated".

**a_stage**: Categorized as "Regional" (a neoplasm that has extended) or "Distant" (a neoplasm that has spread to
parts of the body remote from).

**tumor_size**: The size of tumor (in millimeters).

**regional_node_examined**: The number of examined regional nodes.

**regional_node_positive**: The number of positive reginol nodes.

**survival_month**: The time of a patient with breast cancer is expected to live after their diagnosis (in months).


The dataset comprises a total of \texttt{`r count(survival_df)`} observations, with no missing values in the primary variables analyzed. Firstly, after cleaning and tidying the data, we could figure out the distributions of the data and check for potential outliers or influential points by plotting the distributions of the variables, such as histograms and box plots. We also examine the pairwise relationships between variables.




## Results

As shown in figure \@ref(fig:distribution_of_the_continuous_variables), we can find out that most patients are between 40 and 70 years old, and most of the survival time are larger than 45 months. The number of examined regional nodes for most subjects are smaller than 30, and the subjects with nearly 12 examined regional nodes are the most. It is worth noting that the distributions of both variables `reginol_node_positive` and `tumor_size` are significantly skewed to the right. Over 2500 subjects only have 1 or 2 positive reginol nodes, which is the most frequent number of positive reginol nodes. Most of the tumor sizes are smaller than 50 mm, and we can find that the most frequent size is around 19 mm, followed by around 14 mm.

The figure \@ref(fig:survival_months_by_status) distributed the survival time by the status, showing that survival months are significantly higher for the Alive group compared to the Dead group. According the figure \@ref(fig:tumor_sizes_by_t_stage), from T1 to T3, as the stage changes, both the mean tumor sizes and IQR become larger. At T4 stage, the IQR of tumor sizes is much larger than others, and the mean size is smaller than the mean size at T3 stage. We notice that there are some potential outliers both ar T1 stage and T3 stage. The survival time is longer in the Regional stage, and the Alive group shows higher survival times across both stages by looking at the figure \@ref(fig:survival_months_by_a_stage_based_on_status). In the figure \@ref(fig:tumor_size_by_differentiate), the Undifferentiated group has larger tumor sizes compared to the other categories, while the Well, Moderately, and Poorly differentiated groups show similar distributions with many smaller tumors and numerous high-value outliers. The figure \@ref(fig:relationship_between_age_and_tumor_size_across_status) highlights the differences in tumor size distribution and trends with age between individuals who are alive and those who are deceased. While the "Alive" group shows no significant relationship between age and tumor size, the "Dead" group exhibits a pattern where larger tumors are associated with younger ages. According the figure \@ref(fig:positive_reginol_node_vs_survival_months_across_differentiate), as it changes from undifferentiated to well differentiated, the negative correlation between the number of positive reginol nodes and the survival months becomes weaker.


## Conclusion/Discussion


## Group members' contribution

Leyang and Jinghan focused on statistical methods, building models to extract meaningful insights. Yuechu and Yifei concentrated on data description and visualization, presenting information through clear visuals. All four of us contributed to the writing of the report, integrating our individual efforts into a cohesive final report that reflects both analytical depth and visual clarity.




## Appendix



